data_params:
  catalog: telecommunications
  schema: self_healing_networks
  manuals_volume: device_mans
  towers_volume: towerlocations

model_params:
  prompt: ""  
  endpoint: shn_device_ka

simulation_params:
  n_fieldtechs: 123

